### ISSUE TITLE
Repetitiveness? 

### ISSUE THREAD

**Issue by queeniexiang** [kaybowwow/BoneAppleTeeth#9]
Is it possible to eliminate having to do something like this every single time a condition needs to be applied to a Character:

`	selection2 = Keyboard.readInt();
				if (selection2 == 1) {
				    pat.health += 15;
				    pat.hasDisease = false; 
				}
				if (selection2 == 2) {
				    child1.health += 15;
				    child1.hasDisease = false; 
				}
				if (selection2 == 3) {
				    child2.health += 15;
				    child2.hasDisease = false; 
				}
				if (selection2 == 4) {
				    child3.health += 15;
				    child3.hasDisease = false; 
				}
				if (selection2 == 5) {
				    spouse.health += 15;
				    spouse.hasDisease = false; 
				}`

**Comment by kaybowwow** [comment]
We can create a Character array called familly that has {pat , spouse, child1, child 2, child3}
